# Generated by Django 3.2.5 on 2021-07-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
